# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      checkout_commit:
        description: Commit ID you want to checkout
        type: string
        required: true
      make_command:
        description: Make command to run eg. pre-commit-no-terraform, pre-commit. Default pre-commit
        type: string
        required: false
        default: pre-commit
      make_test_command:
        description: Make test command to run eg. run-test, run-go-module-tests. Skip if this is not set
        type: string
        required: false
      tf_switch_dir:
        description: Specify the location of a .tf file with the terraform constraint defined to automatically download the latest terraform version in the defined range. Defaults to the repos root level.
        type: string
        default: "."
        required: false

jobs:
  CI_Pipeline:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container:
      image: icr.io/goldeneye_images/goldeneye-ci-image:stable
      env:
        TF_VAR_ibmcloud_api_key: ${{ secrets.IBMCLOUD_API_KEY }}
        IC_API_KEY: ${{ secrets.IBMCLOUD_API_KEY }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: true
          ref: ${{ inputs.checkout_commit }}

      # Workaround for https://github.com/actions/runner/issues/2033
      - name: Set ownership
        run: |
          chown -R $(id -u):$(id -g) $PWD

      # Install dependencies
      - name: Install dependencies
        env:
          TFSWITCH_DIRECTORY: ${{ inputs.tf_switch_dir }}
        run: |
          make dependency-install-darwin-linux

      # run pre-commit against all files
      - name: Pre-commit
        run: make ${{ inputs.make_command }}
