name: Terraform-Module-CI

on:
  workflow_call:
    inputs:
      craTarget:
        type: string
        description: "Target directory for CRA scan(accepts comma seperated list for multiple scans). If not provided CRA Scan will not be run"
        required: false
        default: ""
      craGoalIgnoreFile:
        type: string
        description: "CRA Ignore file to use(Used for SCC v1). If not provided checks repo root directory for cra-tf-validate-ignore-goals.json"
        required: false
        default: "cra-tf-validate-ignore-goals.json"
      craRuleIgnoreFile:
        type: string
        description: "CRA Ignore file to use (Used for SCC v2). If not provided checks repo root directory for cra-tf-validate-ignore-rules.json"
        required: false
        default: "cra-tf-validate-ignore-rules.json"
      craSCCv2:
        type: boolean
        description: "Use SCCv2 CRA run-cra-scc-v2.sh"
        required: false
        default: false
      accountID:
        type: string
        description: "CRA scc v2 needs the IBM Cloud Account ID as Input (Default GeDev)"
        required: false
        default: "abac0df06b644a9cabc6e44f55b3880e"
      profileID:
        type: string
        description: "CRA scc v2 needs the Pofile ID as Input. This is the profile ID you want to scan with. Note IDs are region specific ensure you use a US one (Default: US IBM Cloud for Financial Services 1.2.0)"
        required: false
        default: "4c67f813-8723-4029-8b44-848fb989899e"
      craEnvironmentVariables:
        type: string
        description: "An optional list of environment variables to set for CRA, in comma seperated format 'VAR1=value1,VAR2=value2'. This can be used to provide TF_VAR's"
        required: false
        default: ""

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  trigger_ci:
    uses: ./.github/workflows/ci-pipeline.yml
    secrets: inherit
    with:
      checkout_commit: ${{ needs.start-pipeline.outputs.commit_id }}
      make_test_command: run-test

  trigger_infra_tests:
    uses: ./.github/workflows/terraform-test-pipeline.yml
    secrets: inherit
    with:
      checkout_commit: ${{ needs.start-pipeline.outputs.commit_id }}
      craTarget: ${{ inputs.craTarget }}
      craGoalIgnoreFile: ${{ inputs.craGoalIgnoreFile }}
      craRuleIgnoreFile: ${{ inputs.craRuleIgnoreFile }}
      craSCCv2: ${{ inputs.craSCCv2 }}
      accountID: ${{ inputs.accountID }}
      profileID: ${{ inputs.profileID }}
      craEnvironmentVariables: ${{ inputs.craEnvironmentVariables }}
