name: Golang-CI

on:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  trigger_ci:
    uses: ./.github/workflows/ci-pipeline.yml
    with:
      make_command: pre-commit-no-terraform
      make_test_command: run-go-module-tests
