name: Terraform-Module-CI

on:
  workflow_call:
    inputs:
      craTarget:
        type: string
        description: "Target directory for CRA scan. If not provided defaults to root of the repo"
        required: false
        default: ""

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CI_Pipeline:
    name: CI Pipeline
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container:
      image: icr.io/goldeneye_images/goldeneye-ci-image:stable
      env:
        TF_VAR_ibmcloud_api_key: ${{ secrets.IBMCLOUD_API_KEY }}
        IC_API_KEY: ${{ secrets.IBMCLOUD_API_KEY }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NO_CONTAINER: "true"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: true
          # Clone all branches and history. This is needed for the upgrade tests
          fetch-depth: 0

      # Install dependencies
      - name: Install dependencies
        run: |
          make dependency-install-darwin-linux

      # Check for pre-commit updates if it is a renovate PR
      - name: Renovate sweeper
        run: |
          make renovate-sweeper

      # run pre-commit against all files
      - name: Pre-commit
        run: |
          make pre-commit

  Infrastructure_Tests:
    name: Infrastructure Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container:
      image: icr.io/goldeneye_images/goldeneye-ci-image:stable
      env:
        TF_VAR_ibmcloud_api_key: ${{ secrets.IBMCLOUD_API_KEY }}
        IC_API_KEY: ${{ secrets.IBMCLOUD_API_KEY }}
        TOOLCHAIN_ID: ${{ secrets.IAC_GE_OPS_TOOLCHAIN_ID }}
        NO_CONTAINER: "true"
        MZ_INGESTION_KEY: ${{ secrets.MZ_INGESTION_KEY }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: true
          # Clone all branches and history. This is needed for the upgrade tests
          fetch-depth: 0

      # Install dependencies
      - name: Install dependencies
        run: |
          make dependency-install-darwin-linux

      # run CRA scan
      - name: CRA Scan
        run: |
          ci/run-cra.sh "${{ inputs.craTarget }}"

      # run unit tests
      - name: Unit Tests
        run: |
          make run-tests
