on:
  workflow_call:
    inputs:
      required_team:
        description: Team you must be a member of for workflow to pass
        type: string
        default: github-collaborators

jobs:
  Notify-Contributor-Requirements:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/run pipeline' }}
    steps:
      - name: Check Team Membership
        id: check_team
        run: |
          user_in_team=$(curl -X GET -H "Authorization: Bearer ${{secrets.ORG_READER_GH_TOKEN}}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/orgs/${{github.event.organization.login}}/teams/${{inputs.required_team}}/memberships/${{github.actor}}" | jq -r '.state')
          echo "user_in_team=$user_in_team" >> $GITHUB_ENV

      - name: Post Comment and stop workflow if user is not a member
        run: |
          if [[ "${{ env.user_in_team }}" != "active" ]]; then
            curl -X POST -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{github.repository}}/issues/${{github.event.issue.number}}/comments \
            -d "{\"body\": \"@${{github.actor}} you must be in the team **[${{inputs.required_team}}](https://github.com/orgs/${{github.event.organization.login}}/teams/${{inputs.required_team}})** in order to trigger the pipeline.\"}"
            exit 1
          fi
